name: "Quori ROS CI"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: semio-ai/drydoc
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Run a one-line script
        run: ls -a
